services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ./database.sqlite:/app/database.sqlite
      - ./data:/app/data
      - ./frontend:/app/frontend
#    ports:
#      - '8080:8080'
    networks:
      anderdog:
        ipv4_address: 100.50.0.2
networks:
  anderdog:
    driver: bridge
    ipam:
      config:
        - subnet: 100.50.0.0/16
          gateway: 100.50.0.1